```{r load_libraries}
library(dplyr)
library(magrittr)
```


```{r load_data, cache=TRUE}

#batch_id <- args[1] #"2016_04_01_a549_48hr_batch1"
batch_id <- "2016_04_01_a549_48hr_batch1"

metadata_dir <- paste("../..", "metadata", batch_id, sep = "/")

backend_dir <- paste("../..", "backend", batch_id, sep = "/")

per_well_csv <- 
  tibble::data_frame(flist = 
                       list.files(backend_dir, 
                                  pattern = "*augmented.csv", 
                                  recursive = T, full.names = T)
  )

per_well_csv %<>% 
  rowwise() %>%
  mutate(Assay_Plate_Barcode = 
           stringr::str_split(basename(flist), "_")[[1]][1]
         ) %>%
  ungroup()

per_well_csv %<>% inner_join(
  readr::read_csv(paste(metadata_dir, "barcode_platemap.csv", sep = "/")) %>%
    select(Compound_Plate_Map_Name, Assay_Plate_Barcode)
)

per_well_csv %>% 
  count(Compound_Plate_Map_Name) %>%
  knitr::kable()

df <- lapply(per_well_csv$flist %>% normalizePath(), readr::read_csv) %>% bind_rows()

df %<>%
  mutate(Metadata_broad_sample_type = ifelse(is.na(Metadata_broad_sample), "control", "trt")) %>%
  mutate(Metadata_broad_sample = ifelse(Metadata_broad_sample_type =="control", "DMSO", Metadata_broad_sample)) %>%
  mutate(Metadata_mg_per_ml = ifelse(Metadata_broad_sample_type =="control", 0, Metadata_mg_per_ml)) %>%
  mutate(Metadata_mmoles_per_liter = ifelse(Metadata_broad_sample_type =="control", 0, Metadata_mmoles_per_liter)) 
  
feature_cols <-
  colnames(df) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")

metadata_cols <-
  colnames(df) %>%
  stringr::str_subset("^Metadata_")

df %>% 
  count(Metadata_Compound_Plate_Map_Name, Metadata_Plate) %>%
  knitr::kable()
```


```{r variance_threshold}
df <-
  cytominr::select(
    population = df,
    variables = feature_cols,
    sample = df,
    operation = "variance_threshold"
  ) %>%
  dplyr::collect()

feature_cols <-
  colnames(df) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


```{r feature_replicate_scores}
library(foreach)
library(doMC)
doMC::registerDoMC()

calculate_feature_replicate_correlation <- function(data, 
                                                    feature_col, 
                                                    grouping_cols, 
                                                    key_col) {

  nonkey_grouping_cols <- setdiff(grouping_cols, key_col)
  
  correlation_matrix <- 
    data %>%
    dplyr::arrange_(.dots = grouping_cols) %>%
    dplyr::select_(.dots = c(grouping_cols, feature_col)) %>% 
    tidyr::spread_(key_col, feature_col) %>% 
    dplyr::select_(~-dplyr::one_of(nonkey_grouping_cols)) %>%
    cor()
  
  median(correlation_matrix[upper.tri(correlation_matrix)])
}

calculate_feature_replicate_correlations <- 
  function(data, feature_cols, grouping_cols, key_col, split_col) {
  
  foreach::foreach(feature_col = feature_cols, .combine = rbind) %dopar%
    {
      
      data %>%
        split(.[split_col]) %>%
        purrr::map_df(calculate_feature_replicate_correlation, 
                      feature_col = feature_col,
                      grouping_cols = grouping_cols,
                      key_col = key_col) %>% 
        dplyr::mutate(feature_col = feature_col)
    } %>%
      tidyr::gather_(key_col, "pearson", setdiff(names(.), "feature_col")) %>% 
      dplyr::group_by(feature_col) %>% 
      dplyr::summarize_at("pearson", dplyr::funs(median, min, max))
}

```


```{r feature_replicate_scores_calculate, eval=FALSE}
feature_replicate_correlations <-
  df %>%
  filter(Metadata_broad_sample_type == "trt") %>%
  calculate_feature_replicate_correlations(
    feature_cols = feature_cols,
    split_col = "Metadata_Compound_Plate_Map_Name",
    grouping_cols = c("Metadata_Plate", "Metadata_Well"),
    key_col = "Metadata_Plate")

feature_replicate_correlations %>% 
  knitr::kable()

#feature_replicate_correlations  %>% readr::write_csv("feature_replicate_correlations.csv")

```


```{r filter_based_on_feature_replicate_correlations}

if(!exists("feature_replicate_correlations")) {
  stopifnot(file.exists("feature_replicate_correlations.csv"))
  futile.logger::flog.info("Reading feature_replicate_correlations from file.")
  feature_replicate_correlations <- readr::read_csv("feature_replicate_correlations.csv")
}

df %<>% 
  dplyr::select_(.dots = setdiff(x = colnames(df), 
        y = feature_replicate_correlations %>% 
          filter(min < 0.6) %>% 
          magrittr::extract2("feature_col"))
        )

feature_cols <-
  colnames(df) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


```{r correlation_threshold}
df <-
  cytominr::select(
    population = df,
    variables = feature_cols,
    sample = df,
    operation = "correlation_threshold"
  ) %>%
  dplyr::collect()

feature_cols <-
  colnames(df) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


```{r normalize}

futile.logger::flog.threshold(futile.logger::DEBUG)

normalized <-
  cytominr::normalize(
    population = df,
    variables = feature_cols,
    strata =  c("Metadata_Plate"),
    sample = df %>% dplyr::filter(Metadata_broad_sample_type == "control")
  )

# Check if data was normalized correctly by checking if mean of control wells
# is zero
normalized %>%
  dplyr::filter(Metadata_broad_sample_type == "control") %>%
  dplyr::group_by(Metadata_Plate) %>%
  dplyr::summarise_at(feature_cols, mean) %>%
  tidyr::gather(feature_col, error, -Metadata_Plate) %>%
  dplyr::group_by(feature_col) %>%
  dplyr::summarize(error = max(error)) %>%
  dplyr::summarize(max_error = max(error)) 
```


```{r write_gctx}
source("GENE.E.R")

write_gct <- function(df, fname) {
  stopifnot(stringr::str_detect(fname, "gctx$") | stringr::str_detect(fname, "gct$"))
  
  if(file.exists(fname)) {
    file.remove(fname)
  }
  
  df %<>% tidyr::unite(id, Metadata_Plate, Metadata_Well, remove = FALSE)
  
  df %<>% dplyr::mutate_if(is.numeric.Date, as.character)
  
  feature_cols <-
    colnames(df) %>%
    stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
  
  H5close()
  
  mdat <- df %>% dplyr::select_(.dots = feature_cols) %>% data.matrix() %>% t()
  
  column.annotations <- df %>% dplyr::select(matches("^id$|^Metadata_"))
  
  if (stringr::str_detect(fname, "gctx$")) {
    write.gctx(mdat = mdat, column.annotations = column.annotations,  file = fname)
    
  } else {
    n_readouts <- nrow(mdat)
    
    n_samples <- ncol(mdat)
    
    n_row_annot <- 0
    
    n_col_annot <- ncol(column.annotations) - 1 # id is not counted
    
    f <- file(fname, "w")
    
    writeLines("#1.3", con = f)
    
    writeLines(sprintf("%d\t%d\t%d\t%d", n_readouts, n_samples, n_row_annot, n_col_annot), con = f)
    
    close(f)

    readr::write_tsv(x = column.annotations %>% t() %>% as.data.frame() %>% 
                       tibble::rownames_to_column() %>% 
                       dplyr::mutate(rowname = stringr::str_replace(rowname, "Metadata_", "")), 
                     path = fname, append = TRUE, col_names = FALSE)

    readr::write_tsv(x = mdat %>% as.data.frame() %>% tibble::rownames_to_column() , path = fname, append = TRUE)
  }
    
}

```


```{r save_output}
per_well_csv_normalized <-
  per_well_csv %>% 
  dplyr::select(Assay_Plate_Barcode, flist) %>%
  dplyr::rename(Metadata_Assay_Plate_Barcode = Assay_Plate_Barcode) %>%
  dplyr::rowwise() %>%
  dplyr::mutate(flist = stringr::str_replace(flist, "augmented", "normalized")) %>%
  dplyr::ungroup()


normalized %>%
  split(.$Metadata_Assay_Plate_Barcode) %>%
  lapply(function(data) {
    csv_fname <-
      per_well_csv_normalized %>%
      dplyr::filter(Metadata_Assay_Plate_Barcode == data$Metadata_Assay_Plate_Barcode[1]) %>%
      magrittr::extract2("flist")

    futile.logger::flog.info(csv_fname)
    
    gct_fname <- stringr::str_replace(csv_fname, "csv$", "gct")

    futile.logger::flog.info(gct_fname)

    data %>%
      dplyr::arrange(Metadata_Well) %>%
      readr::write_csv(csv_fname)

    data %>%
      write_gct(gct_fname)

  }) %>%
  invisible()

```


